### ISSUE TITLE
How to build

### ISSUE THREAD

**Issue by RobbieArmz** [ChrisAlderson/popcorn-angular-es6#1]
Hi I would like to know how can I build this project. As it seems to be runable on browser but there is some files missing as it follows:

```
GET http://localhost/movieApp/css/app.css 
index.html:11
GET http://localhost/movieApp/node_modules/angular-material/angular-material.min.css 
index.html:32
GET http://localhost/movieApp/main.js 
index.html:12
GET http://localhost/movieApp/node_modules/angular/angular-csp.css 
```

PS: I'm kinda new on JS Apps programming so I don't know all about it and your project seems like a pretty good way of kickstarting it.
Thanks in advance.

**Comment by ChrisAlderson** [comment]
This project isn't really maintained atm. It has been 5 months since I last worked on it. 

If you want to get more into the NodeJS world you can checkout [Thinkster](https://thinkster.io/).
